### DISCUSSION TITLE
Steps for Sveltia CMS setup?

### DISCUSSION THREAD

**Discussion by hectorAguero** [majesticooss/astros#45] [Blog]
Hi, I tried and coudn't setup sveltia-cms with cloudflare workers without previous knowledge of Netlify/Decap CMS.

So, some things I'm not totally sure.

1. I need to create an extra cloudflare worker for the [sveltia-cms-auth](https://github.com/sveltia/sveltia-cms-auth)? So I need to deploy both, this to cloudflare pages and the auth to cloudflare workers? Or the cms-auth is already included?

2. Wich code should I change to make it work? The sveltia-cms-auth mention this config at the end
```yaml
#plublic/admin/config.yml
local_backend: true

logo_url: /logo.svg

backend:
    name: "github"
    repo: zankhq/astros #This for the repo url
    branch: main
    base_url: https://cms.majestico.workers.dev #Also this? with the /callback at the end?
    automatic_deployments: false
```
